// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: gbft.proto

package com.gbft.framework.data;

/**
 * Protobuf type {@code InitShardData}
 */
public final class InitShardData extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:InitShardData)
    InitShardDataOrBuilder {
private static final long serialVersionUID = 0L;
  // Use InitShardData.newBuilder() to construct.
  private InitShardData(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private InitShardData() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new InitShardData();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private InitShardData(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              clusterData_ = com.google.protobuf.MapField.newMapField(
                  ClusterDataDefaultEntryHolder.defaultEntry);
              mutable_bitField0_ |= 0x00000001;
            }
            com.google.protobuf.MapEntry<java.lang.Integer, com.gbft.framework.data.InitShardData.ClusterUnits>
            clusterData__ = input.readMessage(
                ClusterDataDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
            clusterData_.getMutableMap().put(
                clusterData__.getKey(), clusterData__.getValue());
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.gbft.framework.data.Gbft.internal_static_InitShardData_descriptor;
  }

  @SuppressWarnings({"rawtypes"})
  @java.lang.Override
  protected com.google.protobuf.MapField internalGetMapField(
      int number) {
    switch (number) {
      case 1:
        return internalGetClusterData();
      default:
        throw new RuntimeException(
            "Invalid map field number: " + number);
    }
  }
  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.gbft.framework.data.Gbft.internal_static_InitShardData_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.gbft.framework.data.InitShardData.class, com.gbft.framework.data.InitShardData.Builder.class);
  }

  public interface ClusterUnitsOrBuilder extends
      // @@protoc_insertion_point(interface_extends:InitShardData.ClusterUnits)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated int32 values = 2;</code>
     * @return A list containing the values.
     */
    java.util.List<java.lang.Integer> getValuesList();
    /**
     * <code>repeated int32 values = 2;</code>
     * @return The count of values.
     */
    int getValuesCount();
    /**
     * <code>repeated int32 values = 2;</code>
     * @param index The index of the element to return.
     * @return The values at the given index.
     */
    int getValues(int index);
  }
  /**
   * Protobuf type {@code InitShardData.ClusterUnits}
   */
  public static final class ClusterUnits extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:InitShardData.ClusterUnits)
      ClusterUnitsOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ClusterUnits.newBuilder() to construct.
    private ClusterUnits(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ClusterUnits() {
      values_ = emptyIntList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new ClusterUnits();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ClusterUnits(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 16: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                values_ = newIntList();
                mutable_bitField0_ |= 0x00000001;
              }
              values_.addInt(input.readInt32());
              break;
            }
            case 18: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000001) != 0) && input.getBytesUntilLimit() > 0) {
                values_ = newIntList();
                mutable_bitField0_ |= 0x00000001;
              }
              while (input.getBytesUntilLimit() > 0) {
                values_.addInt(input.readInt32());
              }
              input.popLimit(limit);
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          values_.makeImmutable(); // C
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.gbft.framework.data.Gbft.internal_static_InitShardData_ClusterUnits_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.gbft.framework.data.Gbft.internal_static_InitShardData_ClusterUnits_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.gbft.framework.data.InitShardData.ClusterUnits.class, com.gbft.framework.data.InitShardData.ClusterUnits.Builder.class);
    }

    public static final int VALUES_FIELD_NUMBER = 2;
    private com.google.protobuf.Internal.IntList values_;
    /**
     * <code>repeated int32 values = 2;</code>
     * @return A list containing the values.
     */
    @java.lang.Override
    public java.util.List<java.lang.Integer>
        getValuesList() {
      return values_;
    }
    /**
     * <code>repeated int32 values = 2;</code>
     * @return The count of values.
     */
    public int getValuesCount() {
      return values_.size();
    }
    /**
     * <code>repeated int32 values = 2;</code>
     * @param index The index of the element to return.
     * @return The values at the given index.
     */
    public int getValues(int index) {
      return values_.getInt(index);
    }
    private int valuesMemoizedSerializedSize = -1;

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (getValuesList().size() > 0) {
        output.writeUInt32NoTag(18);
        output.writeUInt32NoTag(valuesMemoizedSerializedSize);
      }
      for (int i = 0; i < values_.size(); i++) {
        output.writeInt32NoTag(values_.getInt(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      {
        int dataSize = 0;
        for (int i = 0; i < values_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(values_.getInt(i));
        }
        size += dataSize;
        if (!getValuesList().isEmpty()) {
          size += 1;
          size += com.google.protobuf.CodedOutputStream
              .computeInt32SizeNoTag(dataSize);
        }
        valuesMemoizedSerializedSize = dataSize;
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.gbft.framework.data.InitShardData.ClusterUnits)) {
        return super.equals(obj);
      }
      com.gbft.framework.data.InitShardData.ClusterUnits other = (com.gbft.framework.data.InitShardData.ClusterUnits) obj;

      if (!getValuesList()
          .equals(other.getValuesList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getValuesCount() > 0) {
        hash = (37 * hash) + VALUES_FIELD_NUMBER;
        hash = (53 * hash) + getValuesList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.gbft.framework.data.InitShardData.ClusterUnits parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.gbft.framework.data.InitShardData.ClusterUnits parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.gbft.framework.data.InitShardData.ClusterUnits parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.gbft.framework.data.InitShardData.ClusterUnits parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.gbft.framework.data.InitShardData.ClusterUnits parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.gbft.framework.data.InitShardData.ClusterUnits parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.gbft.framework.data.InitShardData.ClusterUnits parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.gbft.framework.data.InitShardData.ClusterUnits parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.gbft.framework.data.InitShardData.ClusterUnits parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.gbft.framework.data.InitShardData.ClusterUnits parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.gbft.framework.data.InitShardData.ClusterUnits parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.gbft.framework.data.InitShardData.ClusterUnits parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.gbft.framework.data.InitShardData.ClusterUnits prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code InitShardData.ClusterUnits}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:InitShardData.ClusterUnits)
        com.gbft.framework.data.InitShardData.ClusterUnitsOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.gbft.framework.data.Gbft.internal_static_InitShardData_ClusterUnits_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.gbft.framework.data.Gbft.internal_static_InitShardData_ClusterUnits_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.gbft.framework.data.InitShardData.ClusterUnits.class, com.gbft.framework.data.InitShardData.ClusterUnits.Builder.class);
      }

      // Construct using com.gbft.framework.data.InitShardData.ClusterUnits.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        values_ = emptyIntList();
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.gbft.framework.data.Gbft.internal_static_InitShardData_ClusterUnits_descriptor;
      }

      @java.lang.Override
      public com.gbft.framework.data.InitShardData.ClusterUnits getDefaultInstanceForType() {
        return com.gbft.framework.data.InitShardData.ClusterUnits.getDefaultInstance();
      }

      @java.lang.Override
      public com.gbft.framework.data.InitShardData.ClusterUnits build() {
        com.gbft.framework.data.InitShardData.ClusterUnits result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.gbft.framework.data.InitShardData.ClusterUnits buildPartial() {
        com.gbft.framework.data.InitShardData.ClusterUnits result = new com.gbft.framework.data.InitShardData.ClusterUnits(this);
        int from_bitField0_ = bitField0_;
        if (((bitField0_ & 0x00000001) != 0)) {
          values_.makeImmutable();
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.values_ = values_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.gbft.framework.data.InitShardData.ClusterUnits) {
          return mergeFrom((com.gbft.framework.data.InitShardData.ClusterUnits)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.gbft.framework.data.InitShardData.ClusterUnits other) {
        if (other == com.gbft.framework.data.InitShardData.ClusterUnits.getDefaultInstance()) return this;
        if (!other.values_.isEmpty()) {
          if (values_.isEmpty()) {
            values_ = other.values_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureValuesIsMutable();
            values_.addAll(other.values_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.gbft.framework.data.InitShardData.ClusterUnits parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.gbft.framework.data.InitShardData.ClusterUnits) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.Internal.IntList values_ = emptyIntList();
      private void ensureValuesIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          values_ = mutableCopy(values_);
          bitField0_ |= 0x00000001;
         }
      }
      /**
       * <code>repeated int32 values = 2;</code>
       * @return A list containing the values.
       */
      public java.util.List<java.lang.Integer>
          getValuesList() {
        return ((bitField0_ & 0x00000001) != 0) ?
                 java.util.Collections.unmodifiableList(values_) : values_;
      }
      /**
       * <code>repeated int32 values = 2;</code>
       * @return The count of values.
       */
      public int getValuesCount() {
        return values_.size();
      }
      /**
       * <code>repeated int32 values = 2;</code>
       * @param index The index of the element to return.
       * @return The values at the given index.
       */
      public int getValues(int index) {
        return values_.getInt(index);
      }
      /**
       * <code>repeated int32 values = 2;</code>
       * @param index The index to set the value at.
       * @param value The values to set.
       * @return This builder for chaining.
       */
      public Builder setValues(
          int index, int value) {
        ensureValuesIsMutable();
        values_.setInt(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 values = 2;</code>
       * @param value The values to add.
       * @return This builder for chaining.
       */
      public Builder addValues(int value) {
        ensureValuesIsMutable();
        values_.addInt(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 values = 2;</code>
       * @param values The values to add.
       * @return This builder for chaining.
       */
      public Builder addAllValues(
          java.lang.Iterable<? extends java.lang.Integer> values) {
        ensureValuesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, values_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 values = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearValues() {
        values_ = emptyIntList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:InitShardData.ClusterUnits)
    }

    // @@protoc_insertion_point(class_scope:InitShardData.ClusterUnits)
    private static final com.gbft.framework.data.InitShardData.ClusterUnits DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.gbft.framework.data.InitShardData.ClusterUnits();
    }

    public static com.gbft.framework.data.InitShardData.ClusterUnits getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ClusterUnits>
        PARSER = new com.google.protobuf.AbstractParser<ClusterUnits>() {
      @java.lang.Override
      public ClusterUnits parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ClusterUnits(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ClusterUnits> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ClusterUnits> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.gbft.framework.data.InitShardData.ClusterUnits getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public static final int CLUSTERDATA_FIELD_NUMBER = 1;
  private static final class ClusterDataDefaultEntryHolder {
    static final com.google.protobuf.MapEntry<
        java.lang.Integer, com.gbft.framework.data.InitShardData.ClusterUnits> defaultEntry =
            com.google.protobuf.MapEntry
            .<java.lang.Integer, com.gbft.framework.data.InitShardData.ClusterUnits>newDefaultInstance(
                com.gbft.framework.data.Gbft.internal_static_InitShardData_ClusterDataEntry_descriptor, 
                com.google.protobuf.WireFormat.FieldType.INT32,
                0,
                com.google.protobuf.WireFormat.FieldType.MESSAGE,
                com.gbft.framework.data.InitShardData.ClusterUnits.getDefaultInstance());
  }
  private com.google.protobuf.MapField<
      java.lang.Integer, com.gbft.framework.data.InitShardData.ClusterUnits> clusterData_;
  private com.google.protobuf.MapField<java.lang.Integer, com.gbft.framework.data.InitShardData.ClusterUnits>
  internalGetClusterData() {
    if (clusterData_ == null) {
      return com.google.protobuf.MapField.emptyMapField(
          ClusterDataDefaultEntryHolder.defaultEntry);
    }
    return clusterData_;
  }

  public int getClusterDataCount() {
    return internalGetClusterData().getMap().size();
  }
  /**
   * <code>map&lt;int32, .InitShardData.ClusterUnits&gt; clusterData = 1;</code>
   */

  @java.lang.Override
  public boolean containsClusterData(
      int key) {
    
    return internalGetClusterData().getMap().containsKey(key);
  }
  /**
   * Use {@link #getClusterDataMap()} instead.
   */
  @java.lang.Override
  @java.lang.Deprecated
  public java.util.Map<java.lang.Integer, com.gbft.framework.data.InitShardData.ClusterUnits> getClusterData() {
    return getClusterDataMap();
  }
  /**
   * <code>map&lt;int32, .InitShardData.ClusterUnits&gt; clusterData = 1;</code>
   */
  @java.lang.Override

  public java.util.Map<java.lang.Integer, com.gbft.framework.data.InitShardData.ClusterUnits> getClusterDataMap() {
    return internalGetClusterData().getMap();
  }
  /**
   * <code>map&lt;int32, .InitShardData.ClusterUnits&gt; clusterData = 1;</code>
   */
  @java.lang.Override

  public com.gbft.framework.data.InitShardData.ClusterUnits getClusterDataOrDefault(
      int key,
      com.gbft.framework.data.InitShardData.ClusterUnits defaultValue) {
    
    java.util.Map<java.lang.Integer, com.gbft.framework.data.InitShardData.ClusterUnits> map =
        internalGetClusterData().getMap();
    return map.containsKey(key) ? map.get(key) : defaultValue;
  }
  /**
   * <code>map&lt;int32, .InitShardData.ClusterUnits&gt; clusterData = 1;</code>
   */
  @java.lang.Override

  public com.gbft.framework.data.InitShardData.ClusterUnits getClusterDataOrThrow(
      int key) {
    
    java.util.Map<java.lang.Integer, com.gbft.framework.data.InitShardData.ClusterUnits> map =
        internalGetClusterData().getMap();
    if (!map.containsKey(key)) {
      throw new java.lang.IllegalArgumentException();
    }
    return map.get(key);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    com.google.protobuf.GeneratedMessageV3
      .serializeIntegerMapTo(
        output,
        internalGetClusterData(),
        ClusterDataDefaultEntryHolder.defaultEntry,
        1);
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (java.util.Map.Entry<java.lang.Integer, com.gbft.framework.data.InitShardData.ClusterUnits> entry
         : internalGetClusterData().getMap().entrySet()) {
      com.google.protobuf.MapEntry<java.lang.Integer, com.gbft.framework.data.InitShardData.ClusterUnits>
      clusterData__ = ClusterDataDefaultEntryHolder.defaultEntry.newBuilderForType()
          .setKey(entry.getKey())
          .setValue(entry.getValue())
          .build();
      size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, clusterData__);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.gbft.framework.data.InitShardData)) {
      return super.equals(obj);
    }
    com.gbft.framework.data.InitShardData other = (com.gbft.framework.data.InitShardData) obj;

    if (!internalGetClusterData().equals(
        other.internalGetClusterData())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (!internalGetClusterData().getMap().isEmpty()) {
      hash = (37 * hash) + CLUSTERDATA_FIELD_NUMBER;
      hash = (53 * hash) + internalGetClusterData().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.gbft.framework.data.InitShardData parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.gbft.framework.data.InitShardData parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.gbft.framework.data.InitShardData parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.gbft.framework.data.InitShardData parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.gbft.framework.data.InitShardData parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.gbft.framework.data.InitShardData parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.gbft.framework.data.InitShardData parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.gbft.framework.data.InitShardData parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.gbft.framework.data.InitShardData parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.gbft.framework.data.InitShardData parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.gbft.framework.data.InitShardData parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.gbft.framework.data.InitShardData parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.gbft.framework.data.InitShardData prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code InitShardData}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:InitShardData)
      com.gbft.framework.data.InitShardDataOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.gbft.framework.data.Gbft.internal_static_InitShardData_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 1:
          return internalGetClusterData();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMutableMapField(
        int number) {
      switch (number) {
        case 1:
          return internalGetMutableClusterData();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.gbft.framework.data.Gbft.internal_static_InitShardData_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.gbft.framework.data.InitShardData.class, com.gbft.framework.data.InitShardData.Builder.class);
    }

    // Construct using com.gbft.framework.data.InitShardData.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      internalGetMutableClusterData().clear();
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.gbft.framework.data.Gbft.internal_static_InitShardData_descriptor;
    }

    @java.lang.Override
    public com.gbft.framework.data.InitShardData getDefaultInstanceForType() {
      return com.gbft.framework.data.InitShardData.getDefaultInstance();
    }

    @java.lang.Override
    public com.gbft.framework.data.InitShardData build() {
      com.gbft.framework.data.InitShardData result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.gbft.framework.data.InitShardData buildPartial() {
      com.gbft.framework.data.InitShardData result = new com.gbft.framework.data.InitShardData(this);
      int from_bitField0_ = bitField0_;
      result.clusterData_ = internalGetClusterData();
      result.clusterData_.makeImmutable();
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.gbft.framework.data.InitShardData) {
        return mergeFrom((com.gbft.framework.data.InitShardData)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.gbft.framework.data.InitShardData other) {
      if (other == com.gbft.framework.data.InitShardData.getDefaultInstance()) return this;
      internalGetMutableClusterData().mergeFrom(
          other.internalGetClusterData());
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.gbft.framework.data.InitShardData parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.gbft.framework.data.InitShardData) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private com.google.protobuf.MapField<
        java.lang.Integer, com.gbft.framework.data.InitShardData.ClusterUnits> clusterData_;
    private com.google.protobuf.MapField<java.lang.Integer, com.gbft.framework.data.InitShardData.ClusterUnits>
    internalGetClusterData() {
      if (clusterData_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            ClusterDataDefaultEntryHolder.defaultEntry);
      }
      return clusterData_;
    }
    private com.google.protobuf.MapField<java.lang.Integer, com.gbft.framework.data.InitShardData.ClusterUnits>
    internalGetMutableClusterData() {
      onChanged();;
      if (clusterData_ == null) {
        clusterData_ = com.google.protobuf.MapField.newMapField(
            ClusterDataDefaultEntryHolder.defaultEntry);
      }
      if (!clusterData_.isMutable()) {
        clusterData_ = clusterData_.copy();
      }
      return clusterData_;
    }

    public int getClusterDataCount() {
      return internalGetClusterData().getMap().size();
    }
    /**
     * <code>map&lt;int32, .InitShardData.ClusterUnits&gt; clusterData = 1;</code>
     */

    @java.lang.Override
    public boolean containsClusterData(
        int key) {
      
      return internalGetClusterData().getMap().containsKey(key);
    }
    /**
     * Use {@link #getClusterDataMap()} instead.
     */
    @java.lang.Override
    @java.lang.Deprecated
    public java.util.Map<java.lang.Integer, com.gbft.framework.data.InitShardData.ClusterUnits> getClusterData() {
      return getClusterDataMap();
    }
    /**
     * <code>map&lt;int32, .InitShardData.ClusterUnits&gt; clusterData = 1;</code>
     */
    @java.lang.Override

    public java.util.Map<java.lang.Integer, com.gbft.framework.data.InitShardData.ClusterUnits> getClusterDataMap() {
      return internalGetClusterData().getMap();
    }
    /**
     * <code>map&lt;int32, .InitShardData.ClusterUnits&gt; clusterData = 1;</code>
     */
    @java.lang.Override

    public com.gbft.framework.data.InitShardData.ClusterUnits getClusterDataOrDefault(
        int key,
        com.gbft.framework.data.InitShardData.ClusterUnits defaultValue) {
      
      java.util.Map<java.lang.Integer, com.gbft.framework.data.InitShardData.ClusterUnits> map =
          internalGetClusterData().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;int32, .InitShardData.ClusterUnits&gt; clusterData = 1;</code>
     */
    @java.lang.Override

    public com.gbft.framework.data.InitShardData.ClusterUnits getClusterDataOrThrow(
        int key) {
      
      java.util.Map<java.lang.Integer, com.gbft.framework.data.InitShardData.ClusterUnits> map =
          internalGetClusterData().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    public Builder clearClusterData() {
      internalGetMutableClusterData().getMutableMap()
          .clear();
      return this;
    }
    /**
     * <code>map&lt;int32, .InitShardData.ClusterUnits&gt; clusterData = 1;</code>
     */

    public Builder removeClusterData(
        int key) {
      
      internalGetMutableClusterData().getMutableMap()
          .remove(key);
      return this;
    }
    /**
     * Use alternate mutation accessors instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.Integer, com.gbft.framework.data.InitShardData.ClusterUnits>
    getMutableClusterData() {
      return internalGetMutableClusterData().getMutableMap();
    }
    /**
     * <code>map&lt;int32, .InitShardData.ClusterUnits&gt; clusterData = 1;</code>
     */
    public Builder putClusterData(
        int key,
        com.gbft.framework.data.InitShardData.ClusterUnits value) {
      
      if (value == null) { throw new java.lang.NullPointerException(); }
      internalGetMutableClusterData().getMutableMap()
          .put(key, value);
      return this;
    }
    /**
     * <code>map&lt;int32, .InitShardData.ClusterUnits&gt; clusterData = 1;</code>
     */

    public Builder putAllClusterData(
        java.util.Map<java.lang.Integer, com.gbft.framework.data.InitShardData.ClusterUnits> values) {
      internalGetMutableClusterData().getMutableMap()
          .putAll(values);
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:InitShardData)
  }

  // @@protoc_insertion_point(class_scope:InitShardData)
  private static final com.gbft.framework.data.InitShardData DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.gbft.framework.data.InitShardData();
  }

  public static com.gbft.framework.data.InitShardData getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<InitShardData>
      PARSER = new com.google.protobuf.AbstractParser<InitShardData>() {
    @java.lang.Override
    public InitShardData parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new InitShardData(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<InitShardData> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<InitShardData> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.gbft.framework.data.InitShardData getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

