// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: gbft.proto

package com.gbft.framework.data;

public interface InitShardDataOrBuilder extends
    // @@protoc_insertion_point(interface_extends:InitShardData)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>map&lt;int32, .InitShardData.ClusterUnits&gt; clusterData = 1;</code>
   */
  int getClusterDataCount();
  /**
   * <code>map&lt;int32, .InitShardData.ClusterUnits&gt; clusterData = 1;</code>
   */
  boolean containsClusterData(
      int key);
  /**
   * Use {@link #getClusterDataMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.Integer, com.gbft.framework.data.InitShardData.ClusterUnits>
  getClusterData();
  /**
   * <code>map&lt;int32, .InitShardData.ClusterUnits&gt; clusterData = 1;</code>
   */
  java.util.Map<java.lang.Integer, com.gbft.framework.data.InitShardData.ClusterUnits>
  getClusterDataMap();
  /**
   * <code>map&lt;int32, .InitShardData.ClusterUnits&gt; clusterData = 1;</code>
   */

  com.gbft.framework.data.InitShardData.ClusterUnits getClusterDataOrDefault(
      int key,
      com.gbft.framework.data.InitShardData.ClusterUnits defaultValue);
  /**
   * <code>map&lt;int32, .InitShardData.ClusterUnits&gt; clusterData = 1;</code>
   */

  com.gbft.framework.data.InitShardData.ClusterUnits getClusterDataOrThrow(
      int key);
}
